### ISSUE TITLE
ASUS ROG Strix B450i doesn't work

### ISSUE THREAD

**Issue by fooliage** [Mattis-Schulte/hackintosh-asus-b450f#1]
stuck at the Apple  during startup
could you give me some advice?

**Comment by Mattis-Schulte** [comment]
To get a identify the problem you need to enable verbose mode, to do this you need to download Propertree - https://github.com/corpnewt/ProperTree

Then open EFI/OC/config.plist with it and add to NVRAM > Add > 7C436110-AB2A-4BBB-A880-FE41995C9F82 > boot-args “-v”

**Comment by fooliage** [comment]
I caught the error message.
![image](https://user-images.githubusercontent.com/26758630/96890053-d6316a00-14b9-11eb-8860-8d32f11a4b81.png)
And I followed this page: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start
but still stuck at ‘EB|#LOG:EXITBS:START’

**Comment by Mattis-Schulte** [comment]
Try replacing EFI/OC/ACPI/SSDT-EC.aml with this „https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/compiled/SSDT-EC-USBX-DESKTOP.aml“

**Comment by fooliage** [comment]
It didn't work╮(╯▽╰)╭

**Comment by Mattis-Schulte** [comment]
Ok, try next changing Booter > Quirks > SetupVirtualMap in your config.plist to `true`. If this doesn't work change Kernel > Quirks > IncreasePciBarSize to true. 

If it still doesn't work:
> Make sure that SATA mode in your BIOS is set to AHCI and try changing the OS type to `Other OS`. Also, let me know what CPU, GPU, and how many RAM modules you are using.

**Comment by fooliage** [comment]
CPU: 3700X
GPU: RX580 2304sp
RAM: 16Gx2 2666mHz (Kingston)
SATA mode is already set to AHCI. OS type always is Other os.
Now my config.plist looks like this:
[https://gist.github.com/fooliage/ccab28b7744543af200d276345d18f0c](url)

**Comment by Mattis-Schulte** [comment]
So it did work?

**Comment by fooliage** [comment]
It's my fault.I used wrong os installer.
Thanks for your answer!
