### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by leogenot** [Mattis-Schulte/hackintosh-asus-b450f#2]
Hi, I have the exact same motherboard but with Ryzen 7 3800x and rx 5700xt and I can’t boot, I get a blank black screen after some verbose (activated -v in config plist)

**Comment by Mattis-Schulte** [comment]
For navi you also need to add `agdpmod=pikera` to your boot-arguments

**Comment by leogenot** [comment]
> For navi you also need to add `agdpmod=pikera` to your boot-arguments

Okay I’ll try this now

**Comment by leogenot** [comment]
Thank you everything works fine now!
