### ISSUE TITLE
Crackling sound

### ISSUE THREAD

**Issue by S1nPur1ty** [Mattis-Schulte/hackintosh-asus-b450f#3]
Every time when I try to listen to sound related media, I get to hear crackling sounds. I tried to change the alcid with all the numbers given in the supported codecs page (in the AppleALC wiki:
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs)

**Realtek | ALCS1220A | layout 1, 2, 3, 5, 7, 11, 20, 21**

Am I missing out something? Please let me know if you encounter similar issues.

**Comment by Mattis-Schulte** [comment]
The sound works fine for me aside from the fact that I only get stereo sound (I use alcid = 7).
So do you only hear crackling sounds or can you still understand the sound and does the audio work via Bluetooth?

**Comment by S1nPur1ty** [comment]
I just tried my wireless bluetooth headset and everything seems fine with this. However, when I use the headphone jack on my monitor, the sounds is pretty much crackling on my speakers. I have no idea how to specify PCIRoot, but I will be checking it and let you know if I need more help with this. Thanks for the help, very much appreciate it!

**Comment by S1nPur1ty** [comment]
Update: I removed the audio cable from the monitor and connected it straight to my Desktop PC instead. Now its working flawlessly! :)

I think that there is an issue with the AMD kext maybe? What do you think @Mattis-Schulte?

**Comment by Mattis-Schulte** [comment]
I don't think so as audio is almost always AppleALC, even if you're using audio through HDMI / DP. But I guess it doesn't matter anymore.
