### ISSUE TITLE
Big Sur works with OpenCore 0.6.3 

### ISSUE THREAD

**Issue by joschiv** [Mattis-Schulte/hackintosh-asus-b450f#4]
Working EFI as attachment

[EFI.zip](https://github.com/Mattis-Schulte/hackintosh-asus-b450f/files/5512335/EFI.zip)

**Comment by Mattis-Schulte** [comment]
You just changed the Kernel-Patches to the Big Sur beta ones right? Because I tried this a while ago and it didn't work, but I thought for a beta it wasn't worth it anyway.
