### ISSUE TITLE
Black screen after restart.

### ISSUE THREAD

**Issue by JP-Xu** [Mattis-Schulte/hackintosh-asus-b450f#5]
Thanks for updating and sharing!

I login to the system successfully after Big Sur installation, and everything working just fine. However, the screen can't light up ( it is light up, without any image.) when restarted. Btw, I can enter the recovery system. Did you experience this issue? 

Thanks!

**Comment by gustavokei** [comment]
What is your system config (GPU, CPU, mobo, etc)?

I've been using this repo with a B350 Strix without any issues.

**Comment by JP-Xu** [comment]
> What is your system config (GPU, CPU, mobo, etc)?
> 
> I've been using this repo with a B350 Strix without any issues.

I think we are running on a similar specification, B450f + r5 3600. I fixed it by disabling the serial port in BIOS. 
Thanks for your concern!
