### ISSUE TITLE
USB port

### ISSUE THREAD

**Issue by viokula** [Mattis-Schulte/hackintosh-asus-b450f#7]
My USB port which I use to connect my mouse and my keyboard and Bluetooth is only 12Mb/s which is the speed of usb1.0. what is the problem of this?

**Comment by Mattis-Schulte** [comment]
Try this [https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html](https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html)
